inc DriverControlCode.h user;
proc withArgs : (double dist, double turnAmount);
   call Collect;
   drive dist;
   turn turnAmount;
end;
proc withoutArgs;
   call Collect;
end;
func add : (double a, double b);
   ret a+b;
end;
proc autonomous;
   call descorer.set : false;
   var double : a 0.5;
   drive_vel 25;
   turn_vel 30;
   rst 350 degrees;
   turn 350;
   drive 60;
   slp 1000;
   call withArgs : 50,10;
end;
